### ISSUE TITLE
Getting a different result for problem 7.2

### ISSUE THREAD

**Issue by tripathiamritansh** [ArthurZC23/Machine-Learning-A-Probabilistic-Perspective-Solutions#3]
In the following solution https://github.com/ArthurZC23/Machine-Learning-A-Probabilistic-Perspective-Solutions/blob/master/7/2.pdf, my w<sub>1</sub> and w<sub>2</sub> values are as follows:

w<sub>1</sub>=[-4/3 8/3]

w<sub>2</sub>=[-4/3 8/3]

which are different from your solution.

**Comment by ArthurZC23** [comment]
Greetings @tripathiamritansh. From what I can see our results are very close (i.e. the first term of both weight vectors match and the second term is not that different). Furthermore, I think we both get the most important part of the exercise right , which is finding two equal weight vectors. About the numerical result in itself, I will redo the math today and get back to you, ok? Cheers.

**Comment by ArthurZC23** [comment]
@tripathiamritansh, first of all make sure you're using the **fourth printing** of the book and that your dataset is the same as the one in this [link](https://docs.google.com/presentation/d/e/2PACX-1vRSokTDcy-UmVp_2dYMZYqtQc4dazH4gngo8WLOxVuyjTwjAJ3LcZI-xbxBav_6zZECJVosbv5FLFwB/pub?start=false&loop=false&delayms=3000). Assuming we're talking about the same dataset, then I have to stick with my answer for several reasons.
First, if you compute the actual MSE for both results, mine is smaller than yours. Second, if you take a closer look at the x and y values, you will notice that x = 0 predicts the constant w_1 for three negative values of y_1 and y_2. Meanwhile, x = 1 predicts the constant value w_2 for the three positive values of y_1 and y_2. Since the negative and positive values of y have the same frequency count (considering the absolute value), the constant predictions w_1 and w_2 must be symmetrical (i.e. constants with the same value and different signs).  Finally, to justify the numerical values 4/3/ -4/3, you can think this way: x = 0 -> phi(x=0)*w = w_1. w_1 must be the best approximation to (-1, -1, -2). If we had to approximate (-1, -1, -1), then w_1 = -1 = -3/3. If we had to approximate (-2, -2, -2), then w_1 = -2 = -6/3. In the intermediate case where we have to approximate (-1, -1, -2), w_1 = -4/3 seems the best choice possible. The same argument can be made for w_2 or you could stick with the symmetry argument.

**Comment by tripathiamritansh** [comment]
This makes sense!

Thanks for the clarification.
